config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "pages#landing"
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "project", to: "pages#project"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  end

  def about
  end

  def contact
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hugo Mariou's website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://kit.fontawesome.com/37b89652c8.js" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render "shared/navbar"%>
  <%= yield %>
  <%= render "shared/footer"%>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="first">WHO I AM</h1>
<div class="container">
  <div class="texts">
    <p>
      Hi, I'm Hugo!
      I moved to Montréal last year to establish myself in Canada, become a permanent resident, and get the canadian citizenship someday! <br> <br>
      I completed Le Wagon's training and I am now looking for a first experience in web development. <br>
      I am dedicated, passionated and willing to always learn more! <br>
      For more information, you can browse my website or, even better, book me <a class="cvlink" href="<%= contact_path %>">here</a> so that we can have a chat! <br> <br>
      <p>You don't want to go through LinkedIn ? You can check my CV by clicking <a class="cvlink" href="https://docdro.id/576z9ff" download>here</a>!</p>
    </p>
  </div>
  <div class="">
 <%= image_tag "myself.jpg", style: 'display: block; margin: auto; width: 45%;'%>
  </div>

</div>

app/views/pages/contact.html.erb
<h1 class="first"></h1>


<!-- Calendly inline widget begin -->
<div class="calendly-inline-widget" data-url="https://calendly.com/mariou-hugo-job-interview/interview-apointment?hide_gdpr_banner=1" style="min-width:320px;height:630px;"></div>
<script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
<!-- Calendly inline widget end -->

app/views/pages/landing.html.erb
<div class="banner">
<div class ="landingtext">
<h1> Welcome to my website</h1>
<p> Hi, i'm Hugo and I developed this whole website <br> to train as a Web Developer. <br> Here is the result!</p>
</div>

</div>

app/views/pages/project.html.erb
<h1 class="first">MY SKILLS</h1>

<div class="container">

  <div class="card">
    <div class="face face1">
      <div class="content">
        <span class="stars"></span>
        <h2 class="cardtext">HTML</h2>
        <p class="cardtext">The first language I started to dive into the web development</p>
      </div>
    </div>
    <div class="face face2">

    </div>
  </div>

  <div class="card">
    <div class="face face1">
      <div class="content">
        <span class="stars"></span>
        <h2 class="cardtext">CSS</h2>
        <p class="cardtext">Comes in pair with HTML.</p>
      </div>
    </div>
    <div class="face face2">

    </div>
  </div>

    <div class="card">
    <div class="face face1">
      <div class="content">
        <span class="stars"></span>
        <h2 class="cardtext">Javascript</h2>
        <p class="cardtext">I'm currently learning about Javascript and its applications, I love it!</p>
      </div>
    </div>
    <div class="face face2">

    </div>
  </div>

  <div class="card">
    <div class="face face1">
      <div class="content">
        <span class="stars"></span>
        <h2 class="cardtext">Ruby</h2>
        <p class="cardtext">The back-end language I learned from my bootcamp! Also the language I used to create this website!</p>
      </div>
    </div>
    <div class="face face2">

    </div>
  </div>
</div>
<h1 class="first">MY PROJECTS</h1>

<div class="container">
    <div class="card">
    <div class="face face1">
      <div class="content">
        <span class="stars"></span>
        <h2 class="cardtext">Airpnp</h2>
        <p class="cardtext">The first web app I created in group</p>
      </div>
    </div>
    <div class="face face3">

    </div>
  </div>

  <div class="card">
    <div class="face face1">
      <div class="content">
        <span class="stars"></span>
        <h2 class="cardtext">Minder</h2>
        <p class="cardtext">Web app</p>
      </div>
    </div>
    <div class="face face4">

    </div>
  </div>

  <div class="card">
    <div class="face face1">
      <div class="content">
        <span class="stars"></span>
        <h2 class="cardtext">Ruby</h2>
        <p class="cardtext">The back-end language I learned from my bootcamp! Also the language I used to create this website!</p>
      </div>
    </div>
    <div class="face face5">

    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul>
    <li><a href="https://www.instagram.com/m_h_mrou/" target="_blank"><i class="fa-brands fa-instagram icon"></i></a></li>
    <li><a href="https://www.linkedin.com/in/hugo-mariou-devweb/" target="_blank"><i class="fa-brands fa-linkedin icon"></a></i></li>
    <li><a href="https://github.com/HMariou" target="_blank"><i class="fa-brands fa-square-github icon"></i></a></li>
    <li><a href="mailto:mariou.hugo@gmail.com" target="_blank"><i class="fa-regular fa-envelope icon"></i></a></li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<header>
  <div class="logo">
    <a href="<%= root_path%>" class="active">HUGO MARIOU</a>
  </div>
  <div class="hamburger">
    <div class="line"></div>
    <div class="line"></div>
    <div class="line"></div>

  </div>
  <nav class="nav-bar">
    <ul>
      <li>
        <a href="<%= project_path %>">WHAT?</a>
      </li>
      <li>
        <a href="<%= about_path %>">WHO?</a>
      </li>
      <li>
        <a href="<%= contact_path %>">LET'S TALK</a>
      </li>
    </ul>
  </nav>
</header>

<script>
  hamburger = document.querySelector(".hamburger");
  hamburger.onclick = function() {
    navBar = document.querySelector(".nav-bar");
    navBar.classList.toggle("active");
  }
</script>

app/views/shared/savecard.html.erb
<h1 class="first">MY SKILLS</h1>
<div class="project">
  <div class="article-card">
    <div class="content">
      <p class="title"></p>
    </div>
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/CSS3_logo_and_wordmark.svg/1200px-CSS3_logo_and_wordmark.svg.png" alt="article-cover" />
  </div>
    <div class="article-card">
      <div class="content">
        <p class="title"></p>
      </div>
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/2048px-HTML5_logo_and_wordmark.svg.png" alt="article-cover" />
  </div>
    <div class="article-card">
      <div class="content">
        <p class="title"></p>
      </div>
    <img src="https://i0.wp.com/theicom.org/wp-content/uploads/2016/03/js-logo.png?fit=500%2C500&ssl=1&w=640" alt="article-cover" />
    </div>
    <div class="article-card">
      <div class="content">
        <p class="title"></p>
      </div>
    <img src="https://www.betterwebsites.ca/nvimedia/Logo-Ruby.png" alt="article-cover" />
  </div>
  </div>

</div>

<h1 class="first">MY TOOLS</h1>

<div class="project">
  <div class="article-card">
    <div class="content">
      <p class="title"></p>
    </div>
    <img src="https://logos-marques.com/wp-content/uploads/2021/03/GitHub-Logo.png" alt="article-cover" />
  </div>
    <div class="article-card">
      <div class="content">
        <p class="title"></p>
      </div>
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/1280px-Bootstrap_logo.svg.png" alt="article-cover" />
  </div>
    <div class="article-card">
      <div class="content">
        <p class="title"></p>
      </div>
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Heroku_logo.svg/2560px-Heroku_logo.svg.png" alt="article-cover" />
    </div>
    <div class="article-card">
      <div class="content">
        <p class="title"></p>
      </div>
    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Ruby_On_Rails_Logo.svg/1200px-Ruby_On_Rails_Logo.svg.png" alt="article-cover" />
  </div>
  </div>

</div>

<div class="invite">
<p>You don't want to go through LinkedIn ? You can check my CV here!</p>
</div>